# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e706703d881d01ff1842c00e5540576a7d5afddfae03dfcf5a90a1be0465722c96b475d21faa5228fe9c13ee2e5ccceb2e6e2b34040c65adedc5a7d76e2bb339

test:
  secret_key_base: 2b4aedf54d33e6fcceb16caa04ccaffc884ef85bc3b5671b146acbc64e50898cfc81386765d8c42410f261a9ac5fb49a1dc50574bafc33bd95f4231159ce8f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
